### ISSUE TITLE
Netflix only showing in the top left

### ISSUE THREAD

**Issue by CarlHauschke** [tommoor/macflix#1]
The web view browser is only displayed in the top left of the browser Window
I'm running macOS 10.12.5
![Netflix Image](https://i.imgur.com/F0UhxTJ.png)

**Comment by tommoor** [comment]
Hey Carl, this isn't in any way complete - in fact the project is barely started, just so you know :)

Having said that I just pushed a fix for this issue, looks like some Electron API's changed.
